export const STATES = {
  FAQ_HUB: "FAQ_HUB",
  TIME_SELECTION: "TIME_SELECTION",
  COMPRESSED_GUIDE: "COMPRESSED_GUIDE",
  PQA_PROMPT: "PQA_PROMPT",
  PQA_CHALLENGE: "PQA_CHALLENGE",
  PQA_EVALUATION: "PQA_EVALUATION",
  RECOMMENDATION: "RECOMMENDATION",
  EXIT: "EXIT"
};
