export const STATES = {
  START: "START",
  TIME_SELECTION: "TIME_SELECTION",
  COMPRESSED_GUIDE: "COMPRESSED_GUIDE",
  PQA_PROMPT: "PQA_PROMPT",
  PQA_EVALUATION: "PQA_EVALUATION",
  RECOMMENDATION: "RECOMMENDATION",
  EXIT: "EXIT"
};